version: '3.1'

services:

  nginx:
    build:
      context: ./build/nginx
    container_name: dnmp_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/develop/php/:/var/www/html/
      - ~/develop/html/:/var/www/html/html/
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php:php-fpm

  php:
      build: ./build/php
      container_name: dnmp_php
      expose:
        - "9000"
      volumes:
        - ~/develop/php/:/var/www/html/
        - ~/develop/html/:/var/www/html/html/
        - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
        - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./logs/php/:/var/log/php-fpm/:rw
      links:
        - "mysql"
        - "redis"
        - "mongo"

  mysql:
    build:
      context: ./build/mysql
    container_name: dnmp_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./conf/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@123

  redis:
    build:
      context: ./build/redis
    container_name: dnmp_redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs/redis:/var/log/redis

  mongo:
    build:
      context: ./build/mongo
    container_name: dnmp_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Root@123
